name: HIFIR CI
on: [push]
jobs:
  HIFIR-CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Install gtest
        run: |
          sudo apt-get install libgtest-dev
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo " The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo " The workflow is now ready to test your code on the runner."
      - name: run unit tests
        run: |
          cd tests && make DEBUG=2 && cd ..
      - name: build and test examples
        run: |
          cd examples && make DEBUG=2 runall
      - run: echo " This job's status is ${{ job.status }}."
